### POST /auth/login login
POST http://localhost:8082/auth/login
Content-Type: application/x-www-form-urlencoded

username=Zend3&password=duna2

### POST /auth/login login
POST http://localhost:8082/auth/login
Content-Type: application/x-www-form-urlencoded


### Get /transactions list all transactions
GET  http://localhost:8082/transactions?page=0&size=100
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0NDY0MzQxNSwiZXhwIjoxNzQ0NjQ0MDE1fQ.vIMC-mOW-MmuCbXgYlhW99nhnxPB5VHYTFru2WHEVmw

### Get /transactions/{id} get transaction by id=1
GET http://localhost:8082/transactions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0MzAzMDkxMiwiZXhwIjoxNzQzMDMxNTEyfQ.7cBCdghd7HGWFo71N93hG5yZEszWRgXQzFDKQNyzTbE
### Get /transactions/{id} get transaction by id=7
GET http://localhost:8082/transactions/4687
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQwNjgyMDQ0LCJleHAiOjE3NDA2ODU2NDR9.ot-dIAZiwCmBBlUbw4XKLNuEOYqgTiV-gR47eCQTMx4
### Get /transactions/{id} get transaction by id=20
GET http://localhost:8082/transactions/2056
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0MjI0MDEwMSwiZXhwIjoxNzQyNjAwMTAxfQ.bm8EyUhvcL35RPQjR5-DkuiqqCEBRYSzsMCpJvJJKRE

### POST /transactions create a transaction

POST http://localhost:8082/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0MjI0MDYxMywiZXhwIjoxNzQyNjAwNjEzfQ.4gTDI8iHjWb9XRIRUyIdNtt2_AXUbltz6kj-PgVD6qg
Content-Type: application/json

{
    "step": 7,
    "transactionType": "DEPOSIT",
    "amount": 45899784.31,
    "initiator": "4300099464671040",
    "oldBalInitiator" : 45899784.31,
    "newBalInitiator" : 0,
    "recipient": "80-0001943",
    "oldBalRecipient" : 34645746.31,
    "newBalRecipient" : 80545530.62,
    "location": "Recife",
    "transactionDate": "2024-01-20T19:39:20.472276",
    "currency": "USD",
    "fraud": false
}


### DELETE /transactions/{id} delete a transaction by id=20
DELETE http://localhost:8082/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQxOTY0ODAzLCJleHAiOjE3NDIzMjQ4MDN9.91IF_J4GZ5CsVaTL6in2nNoqvIKuGZlLn7WkSrr1eo8

### GET /transactions/filter get transactions by filter
GET http://localhost:8082/transactions/filter?page=0&size=100&location=Singapura
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMDU5MjQzLCJleHAiOjE3NDI0MTkyNDN9.elKZxXYNjl0dokTX0CFz3Pxu8BsHdKlHMdMO1Hm3_94


### GET /transactions/filter get transactions by filter
GET http://localhost:8082/transactions/filter?page=0&size=100&location=Singapura&amount=300
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQwNjgyMDQ0LCJleHAiOjE3NDA2ODU2NDR9.ot-dIAZiwCmBBlUbw4XKLNuEOYqgTiV-gR47eCQTMx4


### GET /transactions/filter get transactions by filter
GET http://localhost:8082/transactions/filter?location=Singapura&amount=300&page=0&size=134
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQwNjgyMDQ0LCJleHAiOjE3NDA2ODU2NDR9.ot-dIAZiwCmBBlUbw4XKLNuEOYqgTiV-gR47eCQTMx4

### POST /transactions/check-fraud check fraud
POST http://localhost:8082/transactions/check-fraud
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0NDY0NDIzOCwiZXhwIjoxNzQ0NjQ0ODM4fQ.NuRvt7X5U-aO1jb5mqlBLooGjS0uP_5r2AcvyhlSsj8
Content-Type: application/json

{
    "id": 30,
    "step": 0,
    "transactionType": "PAYMENT",
    "amount": 1167.99,
    "initiator": "4065896759858389",
    "recipient": "66-0002397",
    "isFraud": false,
    "location": "Seul",
    "transactionDate": "2024-09-14T03:00:43.29947",
    "currency": "SGD"
}

### POST /users/register register a user
POST http://localhost:8082/users/register
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0MzAzMTQ2NiwiZXhwIjoxNzQzMDMyMDY2fQ.LYsITCETO0GrKsswmMcPEA5lmSTTr5RrG5YU29WjsEY
Content-Type: application/json

{
    "username": "ant",
    "password": "anto",
    "email": "anto@gmail.com",
    "firstName": "Antonio",
    "lastName": "Vieira",
    "phoneNumber": "081234567890",
    "address": "Jl. Raya Kebon Jeruk No. 27, Singapura",
    "city": "Arrakys",
    "active": true
}

### GET /users list all users
GET http://localhost:8082/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0MzAzMTQ2NiwiZXhwIjoxNzQzMDMyMDY2fQ.LYsITCETO0GrKsswmMcPEA5lmSTTr5RrG5YU29WjsEY

### GET /users/{id} get user by id=1
GET http://localhost:8082/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQxNzIxODk1LCJleHAiOjE3NDIwODE4OTV9.A75mz1LBLw6tf5pwkZT1RXGIoydw2SSzdIij4SB-IhU

### DELETE /users/{id} delete a user by id=4
DELETE http://localhost:8082/users/0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQxOTY1MDQ3LCJleHAiOjE3NDIzMjUwNDd9.1WcWdyF-mFpU2EQZte0Cm-H5kQ8yaNhxFV_iHHAirR0


### POST /auth/login login
POST http://localhost:8082/auth/login
Content-Type: application/x-www-form-urlencoded

username=Zend3&password=duna2

### Get /pubsub/pub
GET http://localhost:8082/test-pubsub/pub
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0NDQwNzgwNSwiZXhwIjoxNzQ0NDA4NDA1fQ.PFAxW87brRkSDWFYnwB4RP_--_DqVfMNhmyUcAvT_js

### GET /pubsub/sub
GET http://localhost:8082/test-pubsub/sub
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJaZW5kMyIsImlhdCI6MTc0MzQ2MTgwMCwiZXhwIjoxNzQzNDYyNDAwfQ.arVMY6tutnUN3OuPwqWpsUrEaMZsoqAkwUoe6_Etuik
