### POST /auth/login login
POST http://localhost:8082/auth/login
Content-Type: application/x-www-form-urlencoded

username=henbran&password=12345678

### POST /auth/login login
POST http://localhost:8082/auth/login
Content-Type: application/x-www-form-urlencoded


### Get /transactions list all transactions
GET  http://localhost:8082/transactions?page=0&size=100
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMDU5MjQzLCJleHAiOjE3NDI0MTkyNDN9.elKZxXYNjl0dokTX0CFz3Pxu8BsHdKlHMdMO1Hm3_94

### Get /transactions/{id} get transaction by id=1
GET http://localhost:8082/transactions/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMDU5MjQzLCJleHAiOjE3NDI0MTkyNDN9.elKZxXYNjl0dokTX0CFz3Pxu8BsHdKlHMdMO1Hm3_94
### Get /transactions/{id} get transaction by id=7
GET http://localhost:8082/transactions/4687
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQwNjgyMDQ0LCJleHAiOjE3NDA2ODU2NDR9.ot-dIAZiwCmBBlUbw4XKLNuEOYqgTiV-gR47eCQTMx4
### Get /transactions/{id} get transaction by id=20
GET http://localhost:8082/transactions/2056
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQwNjgyMDQ0LCJleHAiOjE3NDA2ODU2NDR9.ot-dIAZiwCmBBlUbw4XKLNuEOYqgTiV-gR47eCQTMx4

### POST /transactions create a transaction

POST http://localhost:8082/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMDU5MjQzLCJleHAiOjE3NDI0MTkyNDN9.elKZxXYNjl0dokTX0CFz3Pxu8BsHdKlHMdMO1Hm3_94
Content-Type: application/json

{
    "step": 7,
    "transactionType": "DEPOSIT",
    "amount": 45899784.31,
    "initiator": "4300099464671040",
    "oldBalInitiator" : 45899784.31,
    "newBalInitiator" : 0,
    "recipient": "80-0001943",
    "oldBalRecipient" : 34645746.31,
    "newBalRecipient" : 80545530.62,
    "location": "Recife",
    "transactionDate": "2024-11-17T19:39:20.472276",
    "currency": "BRL",
    "fraud": false
}


### DELETE /transactions/{id} delete a transaction by id=20
DELETE http://localhost:8082/transactions
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQxOTY0ODAzLCJleHAiOjE3NDIzMjQ4MDN9.91IF_J4GZ5CsVaTL6in2nNoqvIKuGZlLn7WkSrr1eo8

### GET /transactions/filter get transactions by filter
GET http://localhost:8082/transactions/filter?page=0&size=100&location=Singapura
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMDU5MjQzLCJleHAiOjE3NDI0MTkyNDN9.elKZxXYNjl0dokTX0CFz3Pxu8BsHdKlHMdMO1Hm3_94
### GET /transactions/filter get transactions by filter
GET http://localhost:8082/transactions/filter?page=0&size=100&location=Singapura&amount=300
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQwNjgyMDQ0LCJleHAiOjE3NDA2ODU2NDR9.ot-dIAZiwCmBBlUbw4XKLNuEOYqgTiV-gR47eCQTMx4
### GET /transactions/filter get transactions by filter
GET http://localhost:8082/transactions/filter?location=Singapura&amount=300&page=0&size=134
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQwNjgyMDQ0LCJleHAiOjE3NDA2ODU2NDR9.ot-dIAZiwCmBBlUbw4XKLNuEOYqgTiV-gR47eCQTMx4

### POST /transactions/check-fraud check fraud
POST http://localhost:8082/transactions/check-fraud
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQxNzAyNjgzLCJleHAiOjE3NDE3MDYyODN9.uoxoKPwLAY0-B5Tnbrbxu8RK7Pm2iyp4YJcChiX1Gro
Content-Type: application/json

{
  "id": 4687,
  "step": 0,
  "transactionType": "PAYMENT",
  "amount": 522.91,
  "initiator": "4657574490191964",
  "oldBalInitiator": 208468.68,
  "newBalInitiator": 207945.77,
  "recipient": "66-0007049",
  "oldBalRecipient": 606.38,
  "newBalRecipient": 1129.29,
  "isFraud": false,
  "location": "Recife",
  "transactionDate": "2025-02-21T12:52:50.654341",
  "currency": "JPY"
}

### POST /users/register register a user
POST http://localhost:8082/users/register
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMjMzOTQ2LCJleHAiOjE3NDI1OTM5NDZ9._gkt-G5l2O87zKUQztj3gVzeXbaZIjrkXfkQ0MIKZIA
Content-Type: application/json

{
    "username": "Zend3",
    "password": "duna2",
    "email": "bhma@gmail.com",
    "firstName": "Fremen",
    "lastName": "Zendaya",
    "phoneNumber": "081234567890",
    "address": "Jl. Raya Kebon Jeruk No. 27, Singapura",
    "city": "Arrakys",
    "active": true,
    "roles": [{
        "id": 4,
        "role": "ROLE_ADMIN"
    }]
}

### GET /users list all users
GET http://localhost:8082/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMjM0ODEyLCJleHAiOjE3NDI1OTQ4MTJ9.0DqS5qIgs2mNOUF04Ex7tzv-Gzlgq2IdMBZq_RKwv0E

### GET /users/{id} get user by id=1
GET http://localhost:8082/users/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQxNzIxODk1LCJleHAiOjE3NDIwODE4OTV9.A75mz1LBLw6tf5pwkZT1RXGIoydw2SSzdIij4SB-IhU

### DELETE /users/{id} delete a user by id=4
DELETE http://localhost:8082/users/0
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQxOTY1MDQ3LCJleHAiOjE3NDIzMjUwNDd9.1WcWdyF-mFpU2EQZte0Cm-H5kQ8yaNhxFV_iHHAirR0


### GET /roles list all roles
GET http://localhost:8082/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMjM0ODEyLCJleHAiOjE3NDI1OTQ4MTJ9.0DqS5qIgs2mNOUF04Ex7tzv-Gzlgq2IdMBZq_RKwv0E


### POST /roles/register create a role
POST http://localhost:8082/roles/register
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoZW5icmFuIiwiaWF0IjoxNzQyMjMyODM5LCJleHAiOjE3NDI1OTI4Mzl9.XtCABs5p1ro3hbQgSxDoZcslzIKUABIqV5lslEJ9Vmc
Content-Type: application/json

{
    "name": "ROLE_ADMIN"
}