spring:
  application:
    name: fraud-detection
  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_detection_db
    username: bhman
    password: 81132329
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
  sql:
    init:
      mode: never
#   kafka:
#     bootstrap-servers: localhost:9092
#     consumer:
#       group-id: fraud-group
server:
  port: 8082